name: Safe Settings Sync
description: Runs safe-settings sync.
inputs:
  github-token:
    description: 'GitHub access token'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: echo '${{ github.action_path }}'
      shell: bash
    - run: ls -l ${{ github.action_path }}
      shell: bash
    - run: |
        cd ${{ github.action_path }}
        npm run sync:gha
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
